version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: gopress-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gopress
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gopress-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gopress-backend
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=gopress
    networks:
      - gopress-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gopress-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8081
    depends_on:
      - backend
    networks:
      - gopress-network

  nginx:
    image: nginx:alpine
    container_name: gopress-nginx
    ports:
      - "81:81"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - frontend
    networks:
      - gopress-network

networks:
  gopress-network:
    driver: bridge

volumes:
  postgres_data: